set root [file normalize [file dirname [info script]]]
set project_dir [file join $root build tiny_lpu_de1_soc]
file mkdir $project_dir
cd $project_dir
# project_new -overwrite leaves an existing QSF in place.  This project file is
# generated by this script, so remove it to prevent stale device assignments.
file delete -force tiny_lpu_de1_soc.qsf
project_new -overwrite tiny_lpu_de1_soc
set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSEMA5F31C6
set_global_assignment -name TOP_LEVEL_ENTITY de1_soc_top
# Exclude simulation-only real-number conversion helpers guarded with
# `ifndef SYNTHESIS in the model RTL. Quartus does not define this macro by
# default, and real data types are not synthesizable.
set_global_assignment -name VERILOG_MACRO SYNTHESIS
set_global_assignment -name SYSTEMVERILOG_FILE [file join $root src de1_soc_top.sv]
set source_dirs [concat [list [file join $root src]] [glob -nocomplain -types d [file join $root src *]]]
foreach dir $source_dirs {
    # One level is sufficient for TinyLPU's bus modules; archive is deliberately
    # excluded because it contains alternative implementations.
    if {[file tail $dir] ne "archive"} {
        foreach f [glob -nocomplain [file join $dir *.sv]] {
            if {$f ne [file join $root src de1_soc_top.sv] && $f ne [file join $root src lpu_pkg.sv]} {
                set_global_assignment -name SYSTEMVERILOG_FILE $f
            }
        }
    }
}
set_global_assignment -name SEARCH_PATH [file join $root src]
if {0} {
# CVFPU is kept here as a reference source list, but is intentionally disabled:
# the pinned upstream sources use SystemVerilog constructs Quartus Lite 25.1
# does not support. A Quartus-compatible FPU implementation is required before
# this list can be enabled.
set cvfpu [file join $root third_party cvfpu]
set_global_assignment -name SEARCH_PATH [file join $cvfpu src common_cells include]
# The model's FP32 wrappers bind to the repository-pinned CVFPU implementation
# when HAVE_CVFPU is defined. Keep this curated list in the same order as the
# existing simulation makefiles; do not glob the CVFPU tree because it contains
# mutually exclusive test and vendor implementations.
foreach rel {
    src/common_cells/src/cf_math_pkg.sv
    src/common_cells/src/lzc.sv
    src/common_cells/src/rr_arb_tree.sv
    src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
    src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
    vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
    vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
    vendor/cvw/fma/fmalza.sv
    src/fpnew_pkg.sv
    src/fpnew_cast_multi.sv
    src/fpnew_classifier.sv
    src/fpnew_divsqrt_th_32.sv
    src/fpnew_divsqrt_th_64_multi.sv
    src/fpnew_divsqrt_multi.sv
    src/fpnew_fma.sv
    src/fpnew_fma_multi.sv
    src/fpnew_noncomp.sv
    src/fpnew_opgroup_block.sv
    src/fpnew_opgroup_fmt_slice.sv
    src/fpnew_rounding.sv
    src/fpnew_top.sv
} {
    set f [file join $cvfpu $rel]
    if {![file exists $f]} { error "Required CVFPU source is missing: $f. Run: git submodule update --init --recursive" }
    if {[file extension $f] eq ".v"} { set_global_assignment -name VERILOG_FILE $f } else { set_global_assignment -name SYSTEMVERILOG_FILE $f }
}
}
set_location_assignment PIN_AF14 -to CLOCK_50
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to CLOCK_50
set_location_assignment PIN_AJ4 -to KEY[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[0]
set_location_assignment PIN_V16 -to LEDR[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[0]
project_close
