package require -exact qsys 25.1
create_system platform_designer_system
set_project_property DEVICE_FAMILY "Cyclone V"
set_project_property DEVICE 5CSEMA5F31C6
add_instance clk_0 clock_source
set_instance_parameter_value clk_0 clockFrequency {50000000.0}
add_instance jtag_master altera_jtag_avalon_master
add_connection clk_0.clk jtag_master.clk
add_connection clk_0.clk_reset jtag_master.clk_reset
add_interface clk clock sink
set_interface_property clk EXPORT_OF clk_0.clk_in
add_interface reset reset sink
set_interface_property reset EXPORT_OF clk_0.clk_in_reset
add_interface lpu_avalon avalon master
set_interface_property lpu_avalon EXPORT_OF jtag_master.master
save_system platform_designer_system.qsys
