`timescale 1ns/1ps

module mxm_eastbound_adapter #(
    parameter int MXM_SIZE  = 4,
    parameter int PAYLOAD_W = 32
) (
    // Full MXM output matrix.
    input  logic signed [PAYLOAD_W-1:0] mxm_out [MXM_SIZE-1:0][MXM_SIZE-1:0],

    // Which MXM cell should be exposed onto the shared bus this cycle.
    input  logic [$clog2(MXM_SIZE)-1:0] mxm_row_sel,
    input  logic [$clog2(MXM_SIZE)-1:0] mxm_col_sel,

    // Valid generated by external control for MXM as a westbound producer.
    input  logic mxm_valid_in,

    // Single payload+valid feed into westbound_bus.
    output logic [PAYLOAD_W-1:0] mxm_payload,
    output logic                 mxm_valid
);

    // Combinationally pick one MXM output element.
    always_comb begin
        mxm_payload = mxm_out[mxm_row_sel][mxm_col_sel];
        mxm_valid   = mxm_valid_in;
    end

endmodule
