// platform_designer_system.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module platform_designer_system (
		input  wire        clk_clk,                  //        clk.clk
		output wire [31:0] lpu_avalon_address,       // lpu_avalon.address
		input  wire [31:0] lpu_avalon_readdata,      //           .readdata
		output wire        lpu_avalon_read,          //           .read
		output wire        lpu_avalon_write,         //           .write
		output wire [31:0] lpu_avalon_writedata,     //           .writedata
		input  wire        lpu_avalon_waitrequest,   //           .waitrequest
		input  wire        lpu_avalon_readdatavalid, //           .readdatavalid
		output wire [3:0]  lpu_avalon_byteenable,    //           .byteenable
		input  wire        reset_reset_n             //      reset.reset_n
	);

	platform_designer_system_jtag_master #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtag_master (
		.clk_clk              (clk_clk),                  //          clk.clk
		.clk_reset_reset      (~reset_reset_n),           //    clk_reset.reset
		.master_address       (lpu_avalon_address),       //       master.address
		.master_readdata      (lpu_avalon_readdata),      //             .readdata
		.master_read          (lpu_avalon_read),          //             .read
		.master_write         (lpu_avalon_write),         //             .write
		.master_writedata     (lpu_avalon_writedata),     //             .writedata
		.master_waitrequest   (lpu_avalon_waitrequest),   //             .waitrequest
		.master_readdatavalid (lpu_avalon_readdatavalid), //             .readdatavalid
		.master_byteenable    (lpu_avalon_byteenable),    //             .byteenable
		.master_reset_reset   ()                          // master_reset.reset
	);

endmodule
