`timescale 1ns/1ps
`include "lpu_pkg.sv"

module mxm_eastbound_adapter #(
    parameter int MXM_SIZE  = 8,
    parameter int PAYLOAD_W = 32,
    parameter int SCALE_W   = 8
) (
    // Full MXM output matrix.
    input  logic signed [MXM_SIZE-1:0][MXM_SIZE-1:0][PAYLOAD_W-1:0] mxm_out,

    // Which MXM row should be exposed onto the shared bus this cycle.
    input  logic [$clog2(MXM_SIZE)-1:0] mxm_row_sel,
    input  logic [$clog2(MXM_SIZE)-1:0] mxm_col_sel,
    input  logic signed [SCALE_W-1:0]   mxm_scale,

    // Valid generated by external control for MXM as a westbound producer.
    input  logic mxm_valid_in,

    // Packed MXM row feed into eastbound_bus:
    // [255:0] = 8x int32 lanes, [263:256] = fixed-point row scale.
    output logic [MXM_SIZE*PAYLOAD_W+SCALE_W-1:0] mxm_payload,
    output logic                 mxm_valid
);

    logic signed [PAYLOAD_W-1:0] mxm_out_unpacked [MXM_SIZE-1:0][MXM_SIZE-1:0];

    generate
        genvar row;
        genvar col;
        for (row = 0; row < MXM_SIZE; row++) begin : g_row
            for (col = 0; col < MXM_SIZE; col++) begin : g_col
                assign mxm_out_unpacked[row][col] = mxm_out[row][col];
            end
        end
    endgenerate

    // Column select is retained in the control word for now but is intentionally unused:
    // eastbound MXM export now emits a full row per valid cycle.
    always_comb begin
        mxm_payload = '0;
        for (int col = 0; col < MXM_SIZE; col++) begin
            mxm_payload[col*PAYLOAD_W +: PAYLOAD_W] = mxm_out_unpacked[mxm_row_sel][col];
        end
        mxm_payload[MXM_SIZE*PAYLOAD_W +: SCALE_W] = mxm_scale;
        mxm_valid   = mxm_valid_in;
    end

    logic unused_mxm_col_sel;
    assign unused_mxm_col_sel = ^mxm_col_sel;

endmodule
