# Makefile for LPU SXM cocotb testbench

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

VERILOG_SOURCES = $(PWD)/../src/lpu_pkg.sv \
    $(PWD)/../src/cvfpu_fp8_fp32_fma.sv \
    $(PWD)/../src/mac.sv \
    $(PWD)/../src/int_mac.sv \
    $(PWD)/../src/cvfpu_fp8_to_fp32_cast.sv \
    $(PWD)/../src/cvfpu_fp32_fma.sv \
    $(PWD)/../src/acc.sv \
    $(PWD)/../src/mem.sv \
    $(PWD)/../src/mxm.sv \
    $(PWD)/../src/sxm.sv \
    $(PWD)/../src/row_fifo.sv \
    $(PWD)/../src/lut_softmax_exp.sv \
    $(PWD)/../src/lut_softmax_div.sv \
    $(PWD)/../src/softmax.sv \
    $(PWD)/../src/quant.sv \
    $(PWD)/../src/lut_layernorm.sv \
    $(PWD)/../src/vxm_rope.sv \
    $(PWD)/../src/residual_add.sv \
    $(PWD)/../src/vxm.sv \
    $(PWD)/../src/icu.sv \
    $(PWD)/../src/shared_bus_mux.sv \
    $(PWD)/../src/westbound_bus/westbound_bus.sv \
    $(PWD)/../src/westbound_bus/westbound_consumer_decode.sv \
    $(PWD)/../src/eastbound_bus/eastbound_bus.sv \
    $(PWD)/../src/eastbound_bus/eastbound_consumer_decode.sv \
    $(PWD)/../src/eastbound_bus/mxm_eastbound_adapter.sv \
    $(PWD)/../src/lpu.sv \
    $(PWD)/LPU_tb.sv

TOPLEVEL = lpu_cocotb_top
COCOTB_TEST_MODULES = lpu_tb

# Enable VCD waveform dumping
export WAVES=1

include $(shell cocotb-config --makefiles)/Makefile.sim
